### ISSUE TITLE
Small gray bars on movie progressbar under time tooltip

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#1]
When video length is longer than 1 hour and moving cursor over this part of progressbar where 4 digit time changes to 5 digit time (59:59 -> 1:00:01), there will be visible small gray bars behind time tooltip.

[Sample](http://www.six.ee/netipildid/IMG_0139.MOV)

Tested on LG OLEDB6

**Comment by bublikOff** [comment]
Try now
Hope changes helped to solve the issue.

**Comment by argosieger** [comment]
Yes, it seems to be OK now.
Case closed.
P.S. These bars were only on 65OLEDB6, not on my second 55OLEDB6.
