### ISSUE TITLE
Allow to disable auto play next episode 

### ISSUE THREAD

**Issue by bublikOff** [bublikOff/xplay-webos-v2#12]
Allow to disable auto play next episode

**Comment by bublikOff** [comment]
Done

**Comment by argosieger** [comment]
There is something wrong.
If Settings -> Auto play next episode is set to Ask and resuming last episode pops up Play next episode?
To exit from this only Back button helps.

[Sample](http://www,six.ee/netipildid/IMG_0201.MOV)

**Comment by bublikOff** [comment]
Check now please
