### ISSUE TITLE
V1.8 connects to PMS, but V2 does not and keeps trying

### ISSUE THREAD

**Issue by FransTwisk** [bublikOff/xplay-webos-v2#13]
Just tried the new version by clicking on the little flame. It asked me to connect with a new pin through plex.tv/link and after that I saw my server (Synology NAS 416Play running latest PMS). After clicking the server it just stays on "Trying to connect to..."

V1.8 still works. Also tried resetting my settings. Can't really find anything in the PMS logs. What could be wrong?

**Comment by bublikOff** [comment]
Could you share anything from your PMS with my plex account?

**Comment by FransTwisk** [comment]
Guess so! Let me know how I do that. Here are some fresh logs BTW. Let me know if you need debug logs. 

[Plex Media Server.log](https://github.com/bublikOff/xplay-webos-v2/files/1794987/Plex.Media.Server.log)

**Comment by bublikOff** [comment]
https://support.plex.tv/articles/201105738-create-a-new-share/
For the moment I want to check connection checking workflow on the app side ... it was changed a bit since version 1.x

**Comment by FransTwisk** [comment]
Invited. I presumed you are bublikOff on Plex as well ;)

**Comment by bublikOff** [comment]
> Invited. I presumed you are bublikOff on Plex as well ;)
Please change secure connection settings to proffered for a while  
![2018-03-09_032219](https://user-images.githubusercontent.com/1075074/37180221-1b01c3a0-234a-11e8-80d4-b9bb9c909857.png)

**Comment by bublikOff** [comment]
For the moment even official client has problem with connectivity 
![2018-03-09_033056](https://user-images.githubusercontent.com/1075074/37180302-531cafde-234a-11e8-8005-cc8ec878903c.png)

**Comment by bublikOff** [comment]
Seems that there is compatibility problem with latest PMS version ... 
Will check for changes

**Comment by bublikOff** [comment]
Plex reports that your server has two local network addresses 
192.168.0.2:32400 and 192.168.0.3:32400 is this correct?

**Comment by FransTwisk** [comment]
Correct. My NAS has a double network interface. Didn't even think about this might cause problems. 

![image](https://user-images.githubusercontent.com/76724/37195902-f4a00c78-2374-11e8-834f-56166a14919c.png)

**Comment by bublikOff** [comment]
Im just trying to find out what could be the problem.
I was able to connect to your PMS and found one more bug with media details display that was fixed.
![2018-03-09_131216](https://user-images.githubusercontent.com/1075074/37197179-962e112c-239b-11e8-8c5c-943457694366.png)

Anyway ... have you tried to change secure connection settings to proffered for a while? There can be some limits to connect to no secured resources ... it can happen because how test version starts from online source.

**Comment by FransTwisk** [comment]
Tried both but haven't tested extensively yet. I'll try a clean install tonight and fiddle around with some settings.

**Comment by vas82** [comment]
I have the same issue. Unable to connect with beta. Running PMS ver 1.12.0.4829 on mac os, preferred connections selected. Other plex clients have no problem connecting, including XPLAY 1.2.8

**Comment by bublikOff** [comment]
> vas82 
> I have the same issue.
Can you share anything with my account? I'll try to find common things that could lead to the issue

**Comment by vas82** [comment]
I am away from my computer for the weekend, should be able to on monday

**Comment by bublikOff** [comment]
> FransTwisk
Please try again. And please tell me ending number when it freeze ... it will looks like "Trying to connect to SERVER ... 1" or "Trying to connect to SERVER ... 5"

**Comment by FransTwisk** [comment]
`Trying to connect to "server"... **2**`
and then it changed to:
`Trying to connect to "server"... **6**`

**Comment by bublikOff** [comment]
Should work now

**Comment by FransTwisk** [comment]
It does indeed! Thanks :)
