### ISSUE TITLE
Picture Viewer does not start in Folder View

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#15]
Picture Viewer does not start in Folder View..

**Comment by bublikOff** [comment]
Actually Im going to disable "Folder View" for pictures ... as they already have a kind of such view it by default. And official web client does not have "Folder View" at all

**Comment by bublikOff** [comment]
Try now.
"Folder view" disabled for photos.

**Comment by argosieger** [comment]
What can I say...
Case closed.

**Comment by bublikOff** [comment]
Unfortunately there is no other option.
As PMS does not support "folder view" the same way as other libs do.
Photo lib actually a bit differ from other type of libs (music ... movies ... etc)
