### ISSUE TITLE
Set view mode separately for each library

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#17]
In current version if I choose Folder View, then it applies to all Libraries (Movies, Photos, TV-shows etc.)
It would be nice if I can choose View Mode for each Library separately.
For example:
Movies and TV-Shows -> View mode by Type 
Photos -> View mode by Folder

**Comment by bublikOff** [comment]
Have added this functionality in devel version v2.180316

**Comment by argosieger** [comment]
V2.180316 ?
Now is 15.03 in Yekaterinburg?

**Comment by bublikOff** [comment]
Do you think its date in version number?)))
Devel version that available online for testing will be updated in a day)))
Just need to finish some works on folder view for music)

**Comment by argosieger** [comment]
OK-OK-OK :)
It's not date in version number?
