### ISSUE TITLE
Filter "Unwatched"

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#18]
It would be nice to revive filter "Unwatched" as it was in version 1.X.
P.S. There was another filter "Duplicates", but I'm not sure if it is necessary...

EDIT: I found that the filter Unwatched is present, but **only** under TV-shows library.
Please add this filter to every library (including Home videos etc)

**Comment by bublikOff** [comment]
Check now

**Comment by argosieger** [comment]
Perfect.
Case closed.
