### ISSUE TITLE
Folder View: can't move between pages

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#24]
In Folder view: 
List is long and on multiple pages but I cant go to the next page using magic remote scroll button.

**Comment by bublikOff** [comment]
Can you film it?

**Comment by argosieger** [comment]
I can (later), but changing pages dos not work even in View by Type.
Scroll button on Magic Remote does not work.

**Comment by bublikOff** [comment]
You are right about scrolling. It does not work in online version.
When I start direct debug on real TV scrolling works well ... I suppose there is some limits to catching scrolling events

**Comment by argosieger** [comment]
I can make a mistake, but it seems to me that at the beginning it worked.
Or it feels like that...

**Comment by bublikOff** [comment]
I'll check

**Comment by bublikOff** [comment]
Try now

**Comment by argosieger** [comment]
Yes, scrolling between pages works now.
And screensaver also.
But after 2 minutes screensaver switches to system screensaver.
Scrolling case closed.

**Comment by bublikOff** [comment]
Ppl asked me to add screensaver ... there was a discussion about add or not to add.
So ... it was added but disabled by default.
Ppl can choose use or not own screensaver
