### ISSUE TITLE
Music -> Folder View -> sorting by name

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#25]
I have folder where are songs from various artists.
In Folder View, sorting by name, sorts list by Artist name (which is not visible), not by song name.
Maybe is possible to add one column where is Artist name and to add also option to sort by artist name and by song name.

And one more thing. When I press in folder view Play button (on top, near suffle and more actions button), then play starts sorted by song names.

**Comment by bublikOff** [comment]
Im limited by PMS functionality ... and there is no way to sort or do folder filtering in folder view mode
![2018-03-11_161925](https://user-images.githubusercontent.com/1075074/37252732-2e89daf2-2548-11e8-8827-517615db5d8b.png)

I can add extra information about media ... for eg duration ... artist name ... album

**Comment by argosieger** [comment]
OK, then please add extra information.

**Comment by bublikOff** [comment]
It can start only with song name as folder view mode sorts files by file name (in case there is no tag information) or song name

**Comment by bublikOff** [comment]
Ive added artist name.
What about album name ... I think it will make a kind of mess.

**Comment by argosieger** [comment]
In my case, default sorting goes by Artist name.
Why is that?
My songs have tag information and sorting goes by Artist, not by file name or song name?

**Comment by bublikOff** [comment]
Its sorted by artist when view mode is "By Type" ... when you sort it by folder it will have different sorting mode

**Comment by argosieger** [comment]
But I have list sorted by artist even in Folder View.

**Comment by bublikOff** [comment]
I can not put artist in first column ... PMS sorts it by song name 
![2018-03-11_173123](https://user-images.githubusercontent.com/1075074/37253319-11eab33a-2552-11e8-8b62-5581ebad186b.png)

**Comment by argosieger** [comment]
I got soring like that (I don't understand on what this sorting is based on,)

![img_3482](https://user-images.githubusercontent.com/3158788/37253408-ff553168-2539-11e8-98a7-f70f73bfc54f.JPG)

And whatever sorting I chooce, nothing changes and next time I open Sorting there is always selected by Name.

**Comment by bublikOff** [comment]
Share any music lib with me

**Comment by argosieger** [comment]
Now I understand, this list is sorted by file names. 
But not exactly - firs song should be the last by file name.
I sent invitation to you.

**Comment by bublikOff** [comment]
I suppose you have something wrong with your music ... or something else ... PMS sorts it not in alphabet way ... check attached screenshot ... left part is yours and right is mine. And your parts looks strange as PMS does not have sorting in folder view its must be srted correctly ... by song name
![untitled-2](https://user-images.githubusercontent.com/1075074/37253562-1418f4f2-2555-11e8-95fc-38422797b87b.png)

**Comment by argosieger** [comment]
And whatever sorting I chooce, nothing changes and next time I open Sorting there is always selected by Name.

[Sample](http://www.six.ee/netipildid/IMG_3483.MOV)

**Comment by argosieger** [comment]
My files are FLAC files, if this is important. Not MP3.

**Comment by bublikOff** [comment]
Sorting mode in XPlay is just must not be there ... just forgot to disable it for folder view mode.
As you can see original PMS web client does not have sorting for folder view mode

**Comment by argosieger** [comment]
OK.
I can try to delete this Libary and then add again.

**Comment by bublikOff** [comment]
Tracks have originalTitle ... but even with originalTitle it does not make clear why it sorts it this way ... 
![2018-03-11_180333](https://user-images.githubusercontent.com/1075074/37253664-9906ab54-2556-11e8-960e-f26f80fcf9c1.png)

**Comment by bublikOff** [comment]
As a variant I can show originalTitle instead of title

**Comment by argosieger** [comment]
Let's try.
P.S. I deleted library and added again, bau all remains the same.

**Comment by argosieger** [comment]
Anything? 
Did you find out why my list displays abnormally?

**Comment by argosieger** [comment]
I find out that sorting is based on track numbers from file properties.
If **#** number is wrong or even **Part of set** is any number, then sorting goes wrong (or based on these numbers).
I set # numbers to correct order and everything is OK now.
You can close case.

![image](https://user-images.githubusercontent.com/3158788/37270488-ac7c8ef2-25d7-11e8-8305-8f446fc0b0fa.png)
![image](https://user-images.githubusercontent.com/3158788/37270506-bda91ff6-25d7-11e8-9a3f-61134c947299.png)

**Comment by bublikOff** [comment]
I suppose that I can not do anything.
The only way to understand why it plays this way is to ask Plex Inc. but only if official client behave the same. And ask in context of an official client  ... not why XPlay plays this order))
"Tracks View" mode is a bit different mode than "Folder view")
