### ISSUE TITLE
Screensaver starts even when watching movie

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#26]
Screensaver starts even when watching movie.
This is not what expected...

**Comment by bublikOff** [comment]
This is what Ive expected ... issue))) And its good to catch it before LG QA )))

**Comment by bublikOff** [comment]
Must be ok now

**Comment by argosieger** [comment]
Yes, screensaver starts when listening music, but not when watcing movie.
Exactly as it should work.
Case closed.
