### ISSUE TITLE
Screensaver does not start when movie or picture viewer on pause

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#27]
Screensaver does not start when movie on pause...

**Comment by bublikOff** [comment]
I would even add that screensaver for video player must have own enable/disable setting and timeout ... or?

**Comment by argosieger** [comment]
I don’t know..
I thought that yout screensaver is one for all.

**Comment by bublikOff** [comment]
Try now

**Comment by argosieger** [comment]
Good!
Please add keypress to exit from screensaver. 
Currently only cursor move and scroll wheel works.

**Comment by argosieger** [comment]
Good!
Please add keypress to exit from screensaver.
Currently only cursor move and scroll wheel works in Video Player and Foto Viewer.

EDIT: one more bug.
After switching to devel version I need to make at least one cursor move (or button press) on homepage to activate screensaver.
If i do nothing and only wait, then screensaver does not start.

**Comment by bublikOff** [comment]
Check now

**Comment by argosieger** [comment]
Now eveything is OK.
Case closed.
