### ISSUE TITLE
Movie info: width x height

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#29]
Please switch height x width --> width x height.
As in mathematics: always before x-coordinate, then y-coordinate.
**EDIT: Audio information is missing!!!**

![img_3488](https://user-images.githubusercontent.com/3158788/37281689-8f0dc9b2-25fa-11e8-86b1-a49aacde657a.jpg)

**Comment by bublikOff** [comment]
fixed
