### ISSUE TITLE
External .SRT subtitles are not displayed

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#3]
External .SRT subtitles are not displayed.

Tested on LG OLEDB6

**Comment by bublikOff** [comment]
Try now

**Comment by argosieger** [comment]
Now subs are visible!
But... there are wrong symbols for ä, ö etc. No difference what encoding (UTF-8, Windows-1257) I choose
[Sample](url)

**Comment by bublikOff** [comment]
Can you share the subtitles file?

**Comment by argosieger** [comment]
[Better Call Saul - S01E01.est.zip](https://github.com/bublikOff/xplay-webos-v2/files/1790822/Better.Call.Saul.-.S01E01.est.zip)

**Comment by argosieger** [comment]
Is it possible to add black outline to subtitle and to make space bitween lines little bit smaller.
Like it was iin version 1.
[Sample](http://www.six.ee/netipildid/IMG_0151.jpg)

**Comment by bublikOff** [comment]
try now

**Comment by argosieger** [comment]
Super!
?-marks are gone, outline and line spacing are OK.

**Comment by bublikOff** [comment]
Closing issue?

**Comment by argosieger** [comment]
Case closed
