### ISSUE TITLE
Select subtitle: add scrollbar

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#33]
When movie have long list of subtitles, then possible to select only first 13.
Please add possibility to scroll.

![img_0166](https://user-images.githubusercontent.com/3158788/37296587-18b4c6ec-2624-11e8-970b-2d3efa9139cd.jpg)

**Comment by bublikOff** [comment]
Have never seen anything like this)))

**Comment by argosieger** [comment]
It better to be ready...

**Comment by bublikOff** [comment]
To be ready I need a sample for my test movies)

**Comment by argosieger** [comment]
Altered Carbon, i think you can find this.

**Comment by argosieger** [comment]
Altered Carbon, i think you can find this.
This is good example for hardcore tests :)
This TV show is also in 4K and HDR (bitrate about 24 Mbs) but there is scenes (virtual reality) when bitrate rises to 90 Mbs and then TV’s 100 mbs network card is bottle neck and spinning circle is visible after every 5 sec.

**Comment by bublikOff** [comment]
Fixed

**Comment by argosieger** [comment]
Confirmed.
Case closed.
