### ISSUE TITLE
Music player: Previous song button does not work

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#35]
Previous song button does not work.

**Comment by bublikOff** [comment]
Is this the first song in queue?

**Comment by argosieger** [comment]
No-no-no.
When first track is playing, then this button is disabled (as It should be).
There something strange is going one.
Sometimes back button does not do anything, sometimes it goes back to the previous track, but it's impossible to play this track (then play button does not respond).

**Comment by argosieger** [comment]
[Sample](http://www.six.ee/netipildid/IMG_0169.MOV)

**Comment by bublikOff** [comment]
What I do think for the moment ... is to change a bit behavior of music folders in "Folder View" mode ... I do think to make playback directly from folder view without going to album view

**Comment by argosieger** [comment]
When I press Play from Folder View then all remains the same - Prev button does not work

[Sample](http://www.six.ee/netipildid/IMG_0172.MOV)

**Comment by bublikOff** [comment]
1) "Previous song button" should be fixed
2) Playback for music in "Folder View" mode will start directly from "Folder View". The only problem for the moment that playback will not start from the root of music lib ... only sub folders will work OK ... I got the same issue in official web client. I do think to "simulate" playback queue to overcome this problem ... for the root of music libs

**Comment by argosieger** [comment]
Are these changes uploaded and online?
I tried, but it seems to me that in ver 180316 nothing changed.

**Comment by bublikOff** [comment]
check up now

**Comment by argosieger** [comment]
Yes, now is OK!
But, this is not working with selfmade collections (like THE BEST in my PMS)
Then queue is sorted by Artist, not by songs I see in the list.
Do you video sample?

**Comment by bublikOff** [comment]
Ye ... you can film it.
But as I already told there is no ability to sort while "folder view" mode is on

**Comment by argosieger** [comment]
Then no point to film?
There is situation like that:
If I press Play button on top, then queue starts playing sorted by Artist.
If I press play on first song from the list, then song starts playing, but if I press next button on music player, then next song will play also sorted by Artist, not next song in the list I see.
And as I understand, there is nothing to do with it?

**Comment by bublikOff** [comment]
Have you check the same scenario in official (for eg web) client? Does it behave the same way? As the only diff in queue creating for whole folder and clicking on a track in a folder is that the app just tells to PMS start from this element ... and no extra sorting  options provided

**Comment by argosieger** [comment]
I made [sample](http://www.six.ee/netipildid/IMG_0175.MOV).
And Plex web interface behaves the same way - if i choose one song and then press next button on player, then next song will not be next from the list.

But in web there is option to select songs and then next song will be played correctly as in selected list.
![1](https://user-images.githubusercontent.com/3158788/37564211-d00bfdbe-2a99-11e8-9d7e-4644c4037e78.jpg)

**Comment by bublikOff** [comment]
Its impossible to "select" all tracks ... for eg if I have 1k tracks in folder ... the app dos not have the list of of tracks when you just open a lib. It requests only a part of this list. And only while you are scrolling through the all pages it request new and new portions of this list. Of course I replace native queues with own ... what it means ... it will request all elements in folder and create local queue and use it ... and it will play tracks the same way you see it on your screen

**Comment by argosieger** [comment]
It would be nice if you can, because now there is no point if I can't play songs as they are ordered in list I see.

**Comment by bublikOff** [comment]
As for me I dont fully like "folder view" ... folder view mode in PMS is a bit crappy ... sorry for such word ... but its true ... dont have sorting ...  folder view for photos is totally different things actually  ... and etc etc

**Comment by bublikOff** [comment]
I'll probably add an option to choose what type of queue to use in folder view to overcome some PMS native queue drawbacks

**Comment by argosieger** [comment]
It's up to you. 
It works now if I play records which arein internet databases, not selfmade collections.

**Comment by bublikOff** [comment]
As a variant you cat try to ask Plex Inc why different order is used while try to play a track in folder. But you should speak about native clients))) and not asking about why different order in XPlay )))

**Comment by argosieger** [comment]
I understand :)

**Comment by bublikOff** [comment]
Ive added "local" queue type for music player.

![2018-03-21_213303](https://user-images.githubusercontent.com/1075074/37723221-a3b9041a-2d4f-11e8-8455-fe9eb6a37def.png)

Anyway ... in folder view mode the root of library will be played using "local" queue become PMS can not handle tracks in the root ... at least I was not successful trying to play tracks

**Comment by argosieger** [comment]
Local queue is exactly what needed.
Super!
