### ISSUE TITLE
Music -> View by Type -> Play and Shuffle both plays only 21 tracks

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#38]
If I start Shuffle play, then I can press "Next track" button only 21 times.
EDIT: And usual Play also plays only 21 tracks.

**Comment by argosieger** [comment]
What abot that magic number 21?

**Comment by bublikOff** [comment]
Will check later.
Magic number 21 is only because PMS does not return full queue) Only part and the app must re-request queue information every time next media was selected (track switch or next video or photo )

**Comment by argosieger** [comment]
Ok.

**Comment by bublikOff** [comment]
Should be OK now

**Comment by argosieger** [comment]
It is ok now.
Case closed.
