### ISSUE TITLE
Selecting Start from beginning resumes playback

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#4]
When you select Start from beginning, playback will resume, not start from beginning.

Tested on LG OLEDB6

**Comment by bublikOff** [comment]
Need more details. 
TV Show or regular movie? Does it happen all the time or from time to time?

**Comment by argosieger** [comment]
Only TV shows.
And it happens all the time.

**Comment by bublikOff** [comment]
Ask for TV show playback resume only when click on individual episode or when press play whole TV Show or Season?

**Comment by argosieger** [comment]
Current version shows playback resume only when click on individual episode?

**Comment by argosieger** [comment]
Current version shows playback resume only when click on individual episode.
If I start Play from TV Show level, then play resumes from last played episode.
If I start Play from Season level, then play resumes from first episode, what is not correct.
Should be resumed from last played episode as is Show level.
[Sample](http://www.six.ee/netipildid/IMG_0157.MOV)

From episode list only f**irst episode** starts from beginning correctly.
Other episodes do not play from start. If I choose play from start, they resume from last position.
[Sample](http://www.six.ee/netipildid/IMG_0156.MOV)

**Comment by argosieger** [comment]
Current version shows playback resume only when click on individual episode.

In episode list only f**irst episode** starts from beginning correctly.
Other episodes do not play from the start.
If I choose play from the start, they resume from the last position.
[Sample](http://www.six.ee/netipildid/IMG_0156.MOV)

If I start play from TV Show level, then play resumes from last played episode.
If I start play from Season level, then play resumes from the first episode, what is not correct.
Should resume from the last played episode as is in Show level.
[Sample](http://www.six.ee/netipildid/IMG_0157.MOV)

**Comment by bublikOff** [comment]
Try now.
TV Show or Season level it will continue from last position without asking.
But if you want to start some certain episode from beginning you can click on it and it will ask view offset.

**Comment by argosieger** [comment]
It's still not working.
It's only works with first episode of season.

[Sample](http://www.six.ee/netipildid/IMG_0161.MOV)

**Comment by bublikOff** [comment]
Should be OK now
