### ISSUE TITLE
Wrong numbering of tracks (local queue)

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#41]
If I press Next track multiple times (more than tracks on page count) and then scroll to next page, numbering goes wrong.
To restore numbering only refresh helps.

**Comment by argosieger** [comment]
Same result, but shortest way.

[Sample](http://www.six.ee/netipildid/IMG_0181.MOV)

**Comment by bublikOff** [comment]
Should be OK now

**Comment by argosieger** [comment]
Yeah, now is ok.
Case closed.
