### ISSUE TITLE
Colored buttons

### ISSUE THREAD

**Issue by Frepke** [bublikOff/xplay-webos-v2#42]
The colored buttons don't work for me.

**Comment by bublikOff** [comment]
Need more details.
Video player or Photo player?

**Comment by Frepke** [comment]
Sorry, I tried it in the videoplayer

**Comment by bublikOff** [comment]
Should be OK now for video and photo players

**Comment by Frepke** [comment]
Issue solved!

**Comment by argosieger** [comment]
Buttons confirmed, but now dashboard/home is messed up (without big poster).

**Comment by bublikOff** [comment]
Restart and check now
Actually there is an algorithm that does not allow to show duplicate items in "continue watching" and "recently added" blocks. For eg if "recently added" block contains element from "continue watching" the item from "continue watching" will be omitted. And the item will only displayed in "recently added" block with watching progress bar. It allows to show a bit more "recently added" items in some cases

**Comment by argosieger** [comment]
I don't have continue watching section at all (there should be 3 items, I can see them if I open Continue watching from left menu)
![image](https://user-images.githubusercontent.com/3158788/37874139-c7bfc166-3031-11e8-8ce9-0f7044aa5c69.png)

**Comment by bublikOff** [comment]
I understood you but have you tried to restart?
And please share screenshot from continue watching section.
I also faced with this issue today and made some changes that are  helped at least in my situation

**Comment by argosieger** [comment]
Yes, I restarted lot of times.
![img_0184](https://user-images.githubusercontent.com/3158788/37874176-dcb580aa-3032-11e8-9b5c-533c23b3bdf3.jpg)

**Comment by bublikOff** [comment]
Please reload dashboard screen one time.
Ive made some debug points for your user.
I'll check debugs logs

**Comment by argosieger** [comment]
Sh...t, I turned my TV off accidentally. 
Old habbits :)))

**Comment by bublikOff** [comment]
checkup now

**Comment by argosieger** [comment]
Yesss. Now is OK.
Case closed. All of them :))

**Comment by argosieger** [comment]
Wait.....
Why in Continue watching section posters are without progressbar below?

**Comment by bublikOff** [comment]
Its a bit different issue #46
