### ISSUE TITLE
Subtitles VOBSUB PGS

### ISSUE THREAD

**Issue by Frepke** [bublikOff/xplay-webos-v2#43]
Subtitles VOBSUB and PGS not detect well
In the original version of Xplay I've got an transcode warning in the devel version not by every subtitle.
The devel version shows the wrong subtitles (VOBSUB selected and plays .str)

**Comment by bublikOff** [comment]
Please share sample media with my account. I'll check what can be wrong

**Comment by Frepke** [comment]
What's an easy way to create a sample and where to share?

**Comment by bublikOff** [comment]
https://support.plex.tv/articles/201105738-create-a-new-share/
My account name is bublikoff

**Comment by Frepke** [comment]
As sample I use Beauty and the Beast

**Comment by bublikOff** [comment]
Will it be OK if I download it for local tests?

**Comment by Frepke** [comment]
Yes, no problem.

**Comment by Frepke** [comment]
BTW, my server isn't powerful enough for the transcoding

**Comment by bublikOff** [comment]
Ic it from server name))) Im downloading it to my PMS for local tests ...

**Comment by Frepke** [comment]
Yes, but it works for me 😊

**Comment by bublikOff** [comment]
Should handle it now correctly.
PS
Anyway graphical subs are not supported by webOS and they can be handled only using transcoding

**Comment by Frepke** [comment]
Issue solved!
