### ISSUE TITLE
No watch progress bar in libs

### ISSUE THREAD

**Issue by bublikOff** [bublikOff/xplay-webos-v2#46]

**Comment by argosieger** [comment]
Of course... new issue.

Why in "Continue watching" section posters are without progressbar below?
On dashboard there are yellow progress bars.

![img_0185](https://user-images.githubusercontent.com/3158788/37874465-56b3b2c8-3038-11e8-9d3a-6ee0ee5bd941.jpg)

and on dashboard:
![img_0186](https://user-images.githubusercontent.com/3158788/37874468-689d0106-3038-11e8-9b3c-831fb9cc0742.jpg)

**Comment by bublikOff** [comment]
There was no progress bar in all libs.
Just fixed it.

**Comment by argosieger** [comment]
I can’t see bars :((((

**Comment by bublikOff** [comment]
Are you sure?
![2018-03-25_175011](https://user-images.githubusercontent.com/1075074/37875178-0d6cd44c-3055-11e8-8eb7-c1889d7ab441.png)

**Comment by argosieger** [comment]
Now is ok in “Continue watching.”
But no bars in Recently Added.

**Comment by argosieger** [comment]
![img_3512](https://user-images.githubusercontent.com/3158788/37875945-8d6cae58-304e-11e8-9454-236b69097dd2.jpg)
