### ISSUE TITLE
Change Progress bar color on mouse over

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#48]
Enhancement:
Change movie poster Progress bar color on mouse over to darker yellow using Opacity?
In current version mouse over yellow box hides progress bar at all.

**Comment by bublikOff** [comment]
Check up now

**Comment by argosieger** [comment]
Ok, you made red bars...
Is it diffucult to use overlay with opacity.?

**Comment by bublikOff** [comment]
Its possible ... but will it be enough informative on long distance?

**Comment by argosieger** [comment]
I think it is.

**Comment by argosieger** [comment]
Or can you make like this?

![37875546-a040e026-3049-11e8-94fa-5b76ca6447d1](https://user-images.githubusercontent.com/3158788/37875739-1119cf04-304c-11e8-94c4-31f2d04836dc.png)

**Comment by bublikOff** [comment]
Check now ... but ... I dont think its informative 
users will lost sight of it

**Comment by argosieger** [comment]
I like this!
But still no bars in Recentlu Added

**Comment by bublikOff** [comment]
Dashboard screen or when you open "Recently Added" library?
Here is what I do see in "Recently Added" library
![2018-03-25_190120](https://user-images.githubusercontent.com/1075074/37875923-0bf9e686-305f-11e8-8d1f-935e2caf7106.png)

**Comment by argosieger** [comment]
I cant see bars.
Reloaded, turned tv on/off, nothing.
![ffeab22a-3b11-4ec8-8d6c-2707b9777c2f](https://user-images.githubusercontent.com/3158788/37875991-4e074236-304f-11e8-8b1e-2aeae96df1a0.jpeg)

**Comment by bublikOff** [comment]
I suppose that in continue watching you see episode information ... in recently added you see season information.
As a variant I can add only progress of count of watched and unwatched episodes)

**Comment by argosieger** [comment]
So?

**Comment by bublikOff** [comment]
so so)

**Comment by bublikOff** [comment]
check now

**Comment by argosieger** [comment]
I reloaded, but nothing.
Then i turn tv off and on and now like this

![a791787d-8ca9-4247-b0ea-3a497b2e1c55](https://user-images.githubusercontent.com/3158788/37876396-6fe9d9a4-3054-11e8-8ebe-55f12b1c89db.jpeg)

**Comment by argosieger** [comment]
And in Recently Added library also the same problem as in Continue watching

![386da5a1-753a-4e34-b715-f4a03b16a0da](https://user-images.githubusercontent.com/3158788/37876480-8ab946f6-3055-11e8-827e-ec6912dde971.jpeg)

**Comment by bublikOff** [comment]
Check now

**Comment by argosieger** [comment]
Now is Recently added without any progress bar.

**Comment by bublikOff** [comment]
type) wrong "<" instead of ">"
the 3d computer over two weeks is dead because of dead ssd drive) Im trying to fix isses here and repair computer the same time)

**Comment by argosieger** [comment]
Ok, understand.

**Comment by bublikOff** [comment]
Is it ok now?

**Comment by argosieger** [comment]
Recently added is ok now.
What about dashboard’s Recently Added section? There is no bars. Maybe add there also?

And about equal borders. 
You increased mouse over frame bottom border and now it is equal with progressbar height.
It would be nice if all borders are equal. 
Please decrease bottom border and progressbar height, that they will be the same with with mouse over frame left, top and right border.

![94d36989-335a-437d-9d7a-6d6543e98739](https://user-images.githubusercontent.com/3158788/37877668-2b5eaea0-3067-11e8-8e1a-5912cfe3f355.jpeg)

**Comment by argosieger** [comment]
And also inside Tv-shows library there is no progress bars.

**Comment by argosieger** [comment]
And one more strange thing.
I started to warch movie The Shape of Water and then paused it, but no movie poster does not appear on Continue Watching and also there is no progressbar on Recently addad libtary.

![62c80b7e-7f76-4063-8225-168dcc65045f](https://user-images.githubusercontent.com/3158788/37878209-fbe410a0-306d-11e8-8416-ae8a2983feac.jpeg)

![96e3ac99-eda7-4b54-84a8-612798c4ea72](https://user-images.githubusercontent.com/3158788/37878212-06bb54b6-306e-11e8-8e27-459f455706b4.jpeg)

I trie to relod, bur nothing changed.
Only after turn TV on/off everything started to be as it should:

![bda28dae-16a8-4d22-9e9f-7fea6f78f52a](https://user-images.githubusercontent.com/3158788/37878232-42d2008a-306e-11e8-8edd-f618eb30afad.jpeg)

![ff52446c-70f1-45d8-86fd-6645f1c5cc0c](https://user-images.githubusercontent.com/3158788/37878235-4b22a62c-306e-11e8-91a8-33284c090a00.jpeg)

Is it possible to refresh this situation without turning tv on/off?

**Comment by bublikOff** [comment]
Just call refresh from "..."

**Comment by argosieger** [comment]
But automagically?

**Comment by bublikOff** [comment]
Don't think its really necessary and it will be just waste of system resources.
Current version also does not refresh library items.
It only updates dashboard screen from time to time.
But I've "switched it off" in new version just because every time you open dashboard screen it refreshes elements. And you can also call "home" from sections list to refresh dashboard items.
For eg you have started watching movie and stopped it after 10 minutes .... then u open "home" and you will see this movie in "continue watching" block. But to refresh special libs like "continue watching" and " recently added" I can force dont use cached information if you open it after visiting "dashboard" screen.
But anyway it's not the topic to discuss it here "Change Progress bar color on mouse over"

**Comment by argosieger** [comment]
Ok, you are right.
