### ISSUE TITLE
Embedded subtitles transcoded

### ISSUE THREAD

**Issue by sirev86** [bublikOff/xplay-webos-v2#52]
It seems that with the new version all embedded subtitles require transcoding, which is not the case with the current(old) version.

**Comment by bublikOff** [comment]
Check now. Should be ok now

**Comment by sirev86** [comment]
Thanks.. It works

**Comment by sirev86** [comment]
The issue reappeared..

![20180327_204737](https://user-images.githubusercontent.com/37844596/37984923-35f8bc6c-3200-11e8-9e8b-536632256ae8.jpg)

**Comment by bublikOff** [comment]
Have you restarted the app? It may have reused cached resources instead of  new from online.
There were no changes with subtitles since it was fixed an hour ago

**Comment by sirev86** [comment]
I have restarted the app again and seems to work now.
The app was restarted an hour ago as well.. but maybe the tv should be turned off to clear cache for good.
