### ISSUE TITLE
Continue watching issue

### ISSUE THREAD

**Issue by sirev86** [bublikOff/xplay-webos-v2#53]
Continue Watching is not working properly.. I have started a random episode.. watched 5 minutes, then stopped it. It doesn't appear in the continue Watching list.. is this an issue with xplay or pkex server  ?

**Comment by bublikOff** [comment]
Are you speaking about visiting "continue watching" library (section)? on right side? this section does not update items listing automatically. For eg you  have opened "continue watching" section and visit every media ... open details screen and get back and open details of next media ... every time it will request media list from PMS .. not sure that its a good idea to waste system resources everytime you open "continue watching" section and it will increase time of traveling through  "continue watching" section media elements. You can always call section refresh manually.
BUT everytime you open home screen (dashboard) it resets cached elements from  "continue watching" and "Recently added " sections ... and after that it will re-request media elements from those sections

**Comment by sirev86** [comment]
Even if I select Home, Continue watching or title details,this specific title is not updated. I am attaching 3 scrrenshots 
![20180327_201848](https://user-images.githubusercontent.com/37844596/37983758-ffcbf0f8-31fc-11e8-80df-5d4a95370388.jpg)
![20180327_201927](https://user-images.githubusercontent.com/37844596/37983776-0a772d9c-31fd-11e8-95ad-5d98f1f8a2dd.jpg)
![20180327_201947](https://user-images.githubusercontent.com/37844596/37983784-1431441c-31fd-11e8-9bae-353187f09607.jpg)

**Comment by bublikOff** [comment]
Ive made some changes ... try now. It will reset continue watching and recently added after video player stopped 
And have you tried if for eg official web client adds media to "On deck"?

**Comment by argosieger** [comment]
Now there is issue, if I mark video unvatchrd then Recently added abd Continue watching libs shows still this movie with progressbar below.

**Comment by sirev86** [comment]
@bublikOff 
The initial issue is resolved. I have tried the official app and the media is added to deck.

**Comment by sirev86** [comment]
Another thing (more like an enhancement), on Continue Watching lib, can you add the Season/Episode near the show's title (like the official app) ?

**Comment by bublikOff** [comment]
>Now there is issue, if I mark video unwatched then Recently added and Continue watching libs shows still this movie with progressbar below.
fixed 

>Another thing (more like an enhancement), on Continue Watching lib, can you add the Season/Episode near the show's title (like the official app) ?
secondary title changed

**Comment by bublikOff** [comment]
also have changed secondary title in "recently added" ...
check if it will more suitable than date when media was added

**Comment by sirev86** [comment]
It's looking great. Thanks.

**Comment by bublikOff** [comment]
Can be the issue closed?

**Comment by sirev86** [comment]
Sure. Thanks again.
