### ISSUE TITLE
Selecting subtitles during playbacK

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#56]
I have movie with internal subtitles and also have external subtitles and external subtiles are selected from movie details page.
If i select none during playback, there will be no mark near None and external subtitles will displayed.
If i select internal subtitles (wo transcoding), then double subtitles will be displayed - internal and external.

**Comment by bublikOff** [comment]
Check now if its OK now

**Comment by argosieger** [comment]
Not OK!
Last external subtitle rows, which are displayed at this moment when I choose None, does not disappear
And the same situation if I switch to internal subtitles - last rows of external subtitles does not disappear.
Do you need sample?

**Comment by bublikOff** [comment]
Yep ... it would be nice to see a video with issue for better understanding

**Comment by argosieger** [comment]
Not very good, but i hope you understand problem.

[Sample](http://www.six.ee/netipildid/IMG_0208.MOV)

**Comment by bublikOff** [comment]
It seams that I just forgot to update online version... my fault.
Try one more time please

**Comment by bublikOff** [comment]
one more))

**Comment by argosieger** [comment]
Yes, now it seems to be OK.
But one small bug - if I choose None, then there is no checkmark.

**Comment by bublikOff** [comment]
fixed
PS
endless game ... catch the bug)))

**Comment by argosieger** [comment]
I set subtitles to None from movie details page.
Now I start movie and try to set subtitles to external, but nothing happens - no subs visible.
I must to Pause movie and Play again, then external subs are again visible.
There is no this kind of problem with internal subs.

**Comment by bublikOff** [comment]
check now

**Comment by argosieger** [comment]
Yeah.
Case closed.
