### ISSUE TITLE
Enhancement: pressing OK pause/play video

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#57]
Like in ver 1.X, pressing OK pauses and pressing again continues playing.
In current version OK only pops up controls.

**Comment by bublikOff** [comment]
What about logic? How it should react to OK presss? Now we have wake up controls setting
How thye sould combained with OK press?

**Comment by argosieger** [comment]
Like it is in ver 1.X.
First press wakes up controls, second puts in Pause, third plays again.

**Comment by bublikOff** [comment]
What about when only magic remote cursor move wakes up controls? Should it reacts to OK? Why don't you like just use color buttons? It can pause playback instantly

**Comment by argosieger** [comment]
I don't remember how colored buttons are ordered and what color is Pause, what is Play.
And in the dark room it is more difficult.
I think using OK button is the simplest way and I use it in ver 1.X all the time and I like.
If you don't want to port this functionality from ver 1.X, it's up to you. 
But I like it as it is in ver 1.X.

**Comment by bublikOff** [comment]
Check now.
Should focus play/pause button on OK press
Color buttons have the same order like in vide player ) prev, stop, play/pause, next

**Comment by argosieger** [comment]
Yes, now is OK.
Thank you!
Case closed.
