### ISSUE TITLE
External subtitles do not appear when scrolling back

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#6]
External subtitles are not displayed (freezed) when scrolling back (for example from 1:08:21 to 32:48).
Subs are visible again only when to point cursor on progressbar from the first point (1:08:21) to the future time (for example to 1:22:11).

[Sample](http://www.six.ee/netipildid/IMG_0155.MOV)

Tested on LG OLEDB6

**Comment by argosieger** [comment]
External subtitles are not displayed (freezed) when scrolling back (for example from 1:08:21 to 32:48).
Subs are visible again only when to point cursor on progressbar from the first point (1:08:21) to the future time (for example to 1:22:11).

[Sample](http://www.six.ee/netipildid/IMG_0155.MOV)

Tested on LG OLEDB6

**Comment by bublikOff** [comment]
Try now

**Comment by argosieger** [comment]
Now is OK.
Case closed.
