### ISSUE TITLE
Subtitles sync offset adjustment

### ISSUE THREAD

**Issue by andreatondo** [bublikOff/xplay-webos-v2#65]
When external subs are used and they are not in sync with the video, it would be very useful to adjust their offset (eg. +- 0.5-100s) directly from the app.
This is something Plex for Samsung implements, but LG's one does not.

**Comment by bublikOff** [comment]
Done
![2018-06-12_044004](https://user-images.githubusercontent.com/1075074/41262533-ce44749e-6dfa-11e8-8667-fa3fe899839a.png)

**Comment by argosieger** [comment]
It works!
Thanks.

**Comment by theincredibleman** [comment]
Would it be possible to implement this feature for Xplay running on WebOS 3?

**Comment by bublikOff** [comment]
> Would it be possible to implement this feature for Xplay running on WebOS 3?
Its does support all webOS versions but only for external subs.
Emedded subs are not supported.
Email me in case you want to test dev version before LG release it to apps store.
