### ISSUE TITLE
External subtitle font sizes are too big?

### ISSUE THREAD

**Issue by argosieger** [bublikOff/xplay-webos-v2#7]
If to compare ver 1 subtitle sizes with ver 2 subtitles, then for example ver 2 Normal is bigger than ver 1 Normal, ver 2 Big is bigger than version 1 Big etc.
Can you change subtitle sizes like they were in version 1?
In my opinion version 1 sizes were better.

**Comment by argosieger** [comment]
In my opinion now is better.
For me case closed.
But you should decide...

**Comment by bublikOff** [comment]
I almost don't use subtitles)))
