### ISSUE TITLE
Arrow keys navigation

### ISSUE THREAD

**Issue by bublikOff** [bublikOff/xplay-webos-v2#9]
Fix arrow keys navigation

**Comment by argosieger** [comment]
Magic Remote arrow keys do not work...

**Comment by bublikOff** [comment]
I know. Its just remainder for me to backport functionality. The main problem is to backport functionality and use different framework for it.

**Comment by argosieger** [comment]
OK, I understand.

**Comment by mjr0483** [comment]
Same issue, arrow keys do not work.

**Comment by bublikOff** [comment]
Fixed. But probably have some issues in some situation as not fully tested in all possible situations

**Comment by argosieger** [comment]
Can’f open music player from right side (...) with arrows.
Also it would be nice to scroll to the next page of track list when I go down with arrow key.

**Comment by bublikOff** [comment]
>Also it would be nice to scroll to the next page of track list when I go down with arrow key.
Ive done it while making first test in early dev version.
But after we have added seasons list at bottom it will have no sense  ... it will be endless moving up or down in case the list is long ... for eg lets say Ive 300 tracks for unknown artists ... how long it take you to reach the last track or go back  ... to the first track or action buttons? 
I do thing to use channel scrolling buttons would have more logic ... just focus any element in the list and scroll up or down using channel scrolling buttons

**Comment by argosieger** [comment]
You are right.

**Comment by bublikOff** [comment]
Have improved navigation for TV shows, seasons, artists, albums and etc

**Comment by argosieger** [comment]
How can I change pages from bottom with standard remote which have no scroll wheel?

**Comment by bublikOff** [comment]
"pages from bottom"?)

**Comment by argosieger** [comment]
For example long list of music tracks which are on 3 pages.
On bottom there is written 1 of 3
How can i go to the page 2 without scroll wheel?

**Comment by bublikOff** [comment]
CH UP/DOWN were already used in current version for scrolling

**Comment by argosieger** [comment]
I tried regular remote first time :))

**Comment by argosieger** [comment]
For the sake of successful testing, I'm ready to try everything :)))

**Comment by bublikOff** [comment]
don't sacrifice yourself :)))

**Comment by argosieger** [comment]
:))

**Comment by argosieger** [comment]
In Photo Viewer I have to scroll wheel down to show Controls, but it does not work with regular remote CH DOWN.

**Comment by bublikOff** [comment]
Video and Photo players not yet tested.
I'll check how it works there tonight or tomorrow.
For the moment main arrow key navigation algorithm was implemented and tuned only for dashboard and libraries .

**Comment by argosieger** [comment]
Oooukei...

**Comment by bublikOff** [comment]
Navigation in photo player should work now

**Comment by argosieger** [comment]
Yes it works.
Only thing is that CH DOWN moves to next picture and CH UP to previous picture.
This logic maybe should be the opposite?

**Comment by bublikOff** [comment]
The logic of UP/DOWN must be the same in section scrolling or episodes scrolling .... or it will bring only chaos ... at least it my point of view.
 But I do open for discussion

**Comment by argosieger** [comment]
Yes sure, it must be the same everywhere.

**Comment by bublikOff** [comment]
Video player should also works now.
Should but not must lol :)))

**Comment by mjr0483** [comment]
How do you scroll to 2nd page. Right click doesn’t do it. Be nice if it did and there are no arrows like the old version.

**Comment by bublikOff** [comment]
Are you speaking about video player?
Or library elements scrolling?

**Comment by mjr0483** [comment]
Library elements like next page of content

**Comment by bublikOff** [comment]
Have you tried channel up/down buttons? Wheel on magic remote also does the same thing

**Comment by bublikOff** [comment]
> Only thing is that CH DOWN moves to next picture and CH UP to previous picture.
lol) Just tried current version aaaand ... they are inverted lol)))

**Comment by mjr0483** [comment]
Yeah scroll and channel up and down with. 
You can right left from the center ring strange you can’t left and right there to go to the next page. It’s just intuitive to do that. I hate using the scroll on the Magic Mote. 

Thanks

**Comment by bublikOff** [comment]
You should understand that top/bottom and left/right arrow are used to recall side bars.
For eg if I will try to press left button and it will scroll pages again and again ... it will be endless journey to reach sections list.
Of course using left/right buttons is more intuitive but unfortunately its not for this UI design

**Comment by mjr0483** [comment]
Left and right should be page left and right in THAT panel. Then if you want to get to the menus escape out.

**Comment by bublikOff** [comment]
I think will have too heavy logic.
Just press channel up and down ...
And for eg I want to scroll down to page 10 ... I'll have to press right button for long time or many times.
As app will select poster that is located from right side from selected poster ... again and again ...
So 6 posters in row ... how long it will take to reach page 10? Instead of it I can just press channel down 10 times
PS
Hope Ive explained my point of view

**Comment by mjr0483** [comment]
I get it now. Where I get thrown is you think the pages are left and right
and not up and down is because below the two rows is a left and right arrow
with numbers.

It would be fine to stay in the up and down clicks.
If you are p1.1 and a right click brings you to p1.2. From there down would
bring you to p1.8.
If you click down one more time, P2 panels would display and you would be
hovered over p2.1.
And so on and so on.
But if you were on p1.8 and down arrow, nothing.

**Comment by mjr0483** [comment]
My numbers didn't drag properly.
Fixed.

**Comment by bublikOff** [comment]
Not sure ... at least for the moment.
Maybe later I'll add an option to select what navigation algorithm of navigation to use.
For the moment the main aim is to release the app with basic functionality
